export const PROMPTS: string[] = [
  "apple", "banana", "guitar", "piano", "sunset", "mountain", "ocean", "castle",
  "rocket", "bicycle", "pizza", "ice cream", "rainbow", "butterfly", "dragon",
  "robot", "airplane", "volcano", "waterfall", "lighthouse", "cactus", "penguin",
  "giraffe", "elephant", "dolphin", "owl", "peacock", "turtle", "shark", "koala",
  "camera", "umbrella", "sailboat", "hot air balloon", "telescope", "compass",
  "hourglass", "chest", "crown", "mask", "lantern", "feather",
  "surfboard", "skateboard", "roller coaster", "carousel", "ferris wheel",
  "teapot", "toaster", "typewriter", "record player", "maracas",
  "saxophone", "trumpet", "violin", "drum", "microphone", "binoculars",
  "magnifying glass", "key", "lock", "map", "globe", "spaceship", "satellite",
  "lightning", "tornado", "desert", "island", "bridge",
  "windmill", "igloo", "treehouse", "tent", "camper", "helicopter",
  "submarine", "canoe", "kayak", "raft", "train", "tractor", "bulldozer",
  "crane", "escalator", "elevator", "fountain", "statue",
  "pyramid", "sphinx", "totem", "pagoda", "temple",
  "snowflake", "leaf", "flower", "tree", "mushroom", "pineapple", "watermelon",
  "grape", "strawberry", "cherry", "cookie", "cake", "pancake", "waffle",
  "donut", "popcorn", "lollipop", "cotton", "pumpkin", "corn", "sunflower",
  "butterfly", "ladybug", "bee", "snail", "octopus", "whale", "starfish",
  "seahorse", "jellyfish", "crab", "lobster", "parrot", "flamingo", "swan",
  "eagle", "bat", "fox", "wolf", "bear", "tiger", "lion", "zebra", "rhino",
  "hippo", "camel", "llama", "kangaroo", "panda", "monkey", "snake", "chameleon",
  "sushi", "taco", "burger", "fries", "salad", "soup", "steak", "toast",
  "bacon", "egg", "cheese", "bread", "butter", "honey", "jam", "peanut",
  "coffee", "tea", "juice", "milk", "soda", "beer", "wine", "cocktail",
  "bed", "chair", "table", "sofa", "lamp", "clock", "mirror", "rug",
  "curtain", "pillow", "blanket", "towel", "soap", "brush", "comb", "razor",
  "wallet", "purse", "backpack", "suitcase", "hat", "scarf", "glove", "shoe",
  "boot", "sandal", "sock", "belt", "watch", "ring", "necklace", "bracelet",
  "hammer", "saw", "screwdriver", "wrench", "drill", "ladder", "rope", "chain",
  "nail", "screw", "bolt", "spring", "wheel", "axle", "gear", "pulley",
  "sword", "shield", "armor", "helmet", "arrow", "bow", "spear", "axe",
  "cannon", "rifle", "pistol", "bomb", "grenade", "tank", "jeep", "ship",
  "anchor", "rudder", "mast", "oar", "fishing", "net", "basket", "bucket",
  "shovel", "rake", "hoe", "scythe", "plow", "mill", "oven", "stove",
  "fridge", "sink", "faucet", "pipe", "wire", "plug", "socket", "battery",
  "bulb", "laser", "magnet", "motor", "turbine", "generator", "solar", "wind",
];

export function getRandomPrompts(count: number): string[] {
  const shuffled = [...PROMPTS].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
